name: Update Proxy IP

on:
  schedule:
    - cron: '0 17 * * *'  # Setiap hari pukul 00:00 WIB (17:00 UTC)
  workflow_dispatch:  # Memungkinkan untuk menjalankan manual melalui GitHub UI

jobs:
  update-proxies:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Update proxy ip
      env:
        IP_FILE: 'proxyip.txt'
        API_URL: 'https://p01--boiling-frame--kw6dd7bjv2nr.code.run/check?ip={ip}&host=speed.cloudflare.com&port={port}&tls=true'
      run: |
        python update_proxy.py

    - name: Check if update_proxyip.txt exists
      run: |
        if [ -f "update_proxyip.txt" ]; then
          echo "File update_proxyip.txt exists."
          cat update_proxyip.txt
        else
          echo "File update_proxyip.txt not found!"
        fi
